### ISSUE TITLE
create category component 

### ISSUE THREAD

**Issue by Trullfax** [Trullfax/flashbackfiesta#11]
Create a svelte component to choose a category as designed in Figma. The categories should be loaded from the database.

**Required components:**
* Button small
* Title

<img width="888" alt="Bildschirmfoto 2024-08-22 um 12 19 36" src="https://github.com/user-attachments/assets/38d38dbc-31a1-4fb9-8012-896b2ce7ea19">

**Comment by alominty** [comment]
closed, as branch already merged
